### ISSUE TITLE
update the projects sidebar

### ISSUE THREAD

**Issue by vongomben** [OfficineArduinoTorino/officine.cc#5]
at the moment the projects's page sidebar behaves like a standard blogpost. 
This is to be changed.
We should create (I've already created) ```_includes/sidebar-projects.html``` that should feature: 
* [facebook like button](https://developers.facebook.com/docs/plugins/like-button) of the project, and link to the project site (just link if fb page is not present)
* [Embed twitter's poject timeline](https://blog.twitter.com/developer/en_us/topics/tools/2016/embedding-twitter-timelines-just-got-a-lot-easier.html) 
* the twitter or facebook widget is to be triggered by the [markdown project front matter](https://jekyllrb.com/docs/frontmatter/) like/ i.e. ```fb-page:https://www.facebook.com/fablabtorino/``` or ```tw-account:https://www.facebook.com/fablabtorino/```

**Comment by madbob** [comment]
Cfr. CasaJasmina for usage of `fbpage` and `twitter` options
