### ISSUE TITLE
Add an IF to put header images while the GIF is loaded

### ISSUE THREAD

**Issue by vongomben** [OfficineArduinoTorino/officine.cc#6]
It takes some time for the gif to load, not allowing the visitor to see the site. 
Maybe a background upload could fix this?

**Comment by vongomben** [comment]
mm. mergiasti. bene. Ma dove devo mettere le immagini temporanee che vengono caricate prima dell'upload delle gif?

**Comment by madbob** [comment]
In effetti attualmente non c'e' alcuna immagine temporanea, speravo non ce ne fosse piu' bisogno in virtu' delle modifiche del commit di cui sopra. Ma vedendo adesso officine.cc mi sa che non sono sufficienti.

**Comment by madbob** [comment]
cfr. 2b42a22b10d3852937d381cc76eba0c95fa65de0
